server:
  shutdown: graceful
  port: 9090
  forward-headers-strategy: framework

spring:
  application:
    name: voxx-car-service
  #  cache:
  #    type: couchbase
  #  couchbase:
  #    connection-string: couchbase://couchbase-service
  #    password: password
  #    username: Administrator
  #  data:
  #    couchbase:
  #      bucket-name: car-bucket
  #      repositories:
  #        type: none
  #      auto-index: false
  #      type-key: type
  #  kafka:
  #    bootstrap-servers: kafka-service:9092
  #    consumer:
  #      group-id: voxx-core-group
  #      auto-offset-reset: earliest
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
  #      properties:
  #        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  #        spring.json.trusted.packages: "*"
  #        spring.json.use.type.headers: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-service:5432/voxx_car_systems
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8080/realms/voxx-car-systems
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#  liquibase:
#    change-log: classpath:/db/migrations/changelog.xml

keycloak:
  auth-server-url: http://keycloak-service:8080/realms/voxx-car-systems
  client-id: voxx-car-client
  client-secret: your-client-secret
  grant-type: password

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: voxx-car-client

logging:
  level:
    org.springframework.security: trace
    root: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs

security:
  whitelist:
    urls:
      - /swagger-ui.html
      - /swagger-ui/**
      - /v3/api-docs/**
      - /v3/api-docs
      - /ws/**
      - /ws
      - /ws/info/**
      - /ws/info
      - /auth
      - /auth/**

app:
  cors:
    allowed:
      origins: "https://voxxcarsystems.online"
      methods: "GET,POST,OPTIONS"
      headers: "Content-Type,Authorization"
      credentials: true

#kafka:
#  topic:
#    model-created: model-created-topic
#    model-updated: model-updated-topic
#    model-deleted: model-deleted-topic
#    marka-created: marka-created-topic
#    marka-updated: marka-updated-topic
#    marka-deleted: marka-deleted-topic
#    firma-created: firma-created-topic
#    firma-updated: firma-updated-topic
#    firma-deleted: firma-deleted-topic
#    adres-created: adres-created-topic
#    adres-updated: adres-updated-topic
#    adres-deleted: adres-deleted-topic
#    iletisim-created: iletisim-created-topic
#    iletisim-updated: iletisim-updated-topic
#    iletisim-deleted: iletisim-deleted-topic
#    arac-filo-created: arac-filo-created-topic
#    arac-filo-updated: arac-filo-updated-topic
#    arac-filo-deleted: arac-filo-deleted-topic
#    bakim-created: bakim-created-topic
#    bakim-updated: bakim-updated-topic
#    bakim-deleted: bakim-deleted-topic
#    kaza-created: kaza-created-topic
#    kaza-updated: kaza-updated-topic
#    kaza-deleted: kaza-deleted-topic
#    sigorta-created: sigorta-created-topic
#    sigorta-updated: sigorta-updated-topic
#    sigorta-deleted: sigorta-deleted-topic
#    mtv-created: mtv-created-topic
#    mtv-updated: mtv-updated-topic
#    mtv-deleted: mtv-deleted-topic
#    hasar-created: hasar-created-topic
#    hasar-updated: hasar-updated-topic
#    hasar-deleted: hasar-deleted-topic
#    muayene-created: muayene-created-topic
#    muayene-updated: muayene-updated-topic
#    muayene-deleted: muayene-deleted-topic
#    alisfaturasi-created: alisfaturasi-created-topic
#    alisfaturasi-updated: alisfaturasi-updated-topic
#    alisfaturasi-deleted: alisfaturasi-deleted-topic
#    filodancikis-created: filodancikis-created-topic
#    filodancikis-updated: filodancikis-updated-topic
#    filodancikis-deleted: filodancikis-deleted-topic
#    arackullanan-created: arackullanan-created-topic
#    arackullanan-updated: arackullanan-updated-topic
#    arackullanan-deleted: arackullanan-deleted-topic